Deep Learning is Driving the New Agriculture Revolution

As the human population continues to spawn— [to perhaps nearly 10 billion by 2050](http://www.prb.org/Publications/Datasheets/2016/2016-world-population-data-sheet.aspx) —the size of the planet stays the same, meaning the same amount of land must somehow support more people. Intensified further by the volatility of extreme weather events and the resulting water shortage, humanity is going to have a hard time finding ways to support itself. And with the increasing urbanization of life and more humans moving to live in the cities, more and more people will be less engaged with food production.

Although the harsh reality of food shortage is one of the biggest crises facing civilization, it is nothing new. Humanity has been dealing with food shortage for all its history, but nonetheless, has found ways to overcome this through agriculture and the invention of fertilizers and mechanized farming to speed up processes. But as the global population continues to increase and expand its economic activity along with the development of transport systems and urban structures, the area of vital cropland for food production is likely to [decrease and become increasingly unavailable.](https://ourworldindata.org/land-use-in-agriculture/) In the last 40 years, the world lost a third of its arable land due to land degradation caused by [pollution and erosion](http://grantham.sheffield.ac.uk/soil-loss-an-unfolding-global-disaster/). In developed countries, the area of arable land in crop production has been declining since the mid-eighties, according to reports from the [United Nations Food and Agricultural Organization](http://www.fao.org/docrep/016/ap106e/ap106e.pdf). So with resources likely to become scarcer, there's going to need to make more efficient use of the current amount of land, water, and resources left. So how can we plan, measure, and more efficiently allocate precious resources where they are most needed— especially for food production — before it’s too late? 

###Deep Learning Meets Agriculture

More and more of today's farmers are embracing advanced technology to decrease their overall labor and become more efficient. Farmers are getting help from researchers and scientists who have turned the keen eye of AI toward agriculture, using deep learning applications to not only predict crop outputs but also to monitor water levels around the world and help detect crop diseases before one spreads. 

Deep learning is an incredibly powerful method of computing that involves “training” a computational model to recognize complex patterns in data. Using deep learning for imagery techniques allows a computer to recognize what the important "features" of the images are and their locations using a training dataset. In agriculture, specific information and patterns across vast amounts of images from drones or satellites can be used to understand better how crops are growing globally and over time.

Here are examples of how innovations pioneered by deep learning are making significant advances in the agriculture industry:

####Improving Farming Efficiency
Agricultural output is affected by various factors including soil, weather, seed, cultivation practices, irrigation, fertilizers, pesticides, weeds, disease, harvesting, and post-harvesting. Scientists from the start-up [IntelinAir, Inc](http://www.intelinair.com/) are helping farmers quickly and accurately pinpoint a problem using drones and airplanes with MRI-like imaging called, Ag-MRI™, to help identify anomalies within a field in an accurate and concise manner. Their propriety software takes thousands of visible and infrared images of each field, feeds them into an algorithm that then compiles them into a single image of the field to show which areas are damaged, have weeds or in need of more nutrients.  Once the extent of the problem has been identified in a field, farmers can just focus on treating those areas, and will ultimately help farmers increase efficiency and productivity.

####Crop Diseases
Deep learning algorithms can be used to identify plant diseases. For example, [scientists from Penn State and the Swiss Federal Institute of Technology](http://news.psu.edu/story/429727/2016/10/04/research/artificial-intelligence-could-help-farmers-diagnose-crop-diseases) are making it possible for rapid crop disease identification using smartphones. Using a deep learning approach, they fed more than 5,000 images of diseased and healthy plants (from a dataset containing 14 crops and 26 diseases) into a large cluster of computers and trained it to recognize specific plant diseases with a high degree of accuracy.

These recent advances in technology could have particular benefits for farmers in developing regions, in which plant diseases can have devastating consequences for smallholder farmers whose livelihoods depend on healthy crops. Smallholder farmers account for more than 80 percent of agricultural production in developing regions, and as many as half of the hungriest population live in smallholder farming households. Such small-scale operations with fewer are more prone to the devastating effects of crop disease, which can wipe out entire crops, resulting in famine in the area. Rapid identification remains difficult due to the lack of the necessary infrastructure in smallholder farms. 

####Forecasting Commodities Markets
A group of researchers from the [Descartes Labs](http://www.descarteslabs.com/) in New Mexico is using deep learning technology to analyze images faster and predict the future. The aim is to make “a living map of all the world’s agriculture” using lots of computer power and a combination of satellite imagery from Landsat 8 and Planet Labs. The technology is designed to forecast commodity crop production more accurately and more frequently using patterns over time. 

####Reducing the Use of Pesticides
As weeds are becoming more resistant to herbicides, chemical treatments are becoming less available. To address this problem, Blue River Technology from Silicon Valley came up with a deep learning solution, called the [LettuceBot](http://smartmachines.bluerivert.com/), that can help minimize the use of pesticides and herbicides. The LettuceBot rolls through a field photographing 5,000 young plants a minute and identifies each sprout as lettuce or a weed using algorithms and machine vision. It can automatically pinpoint weeds, unfledged sprouts, and overcrowded areas and then apply tiny doses of herbicide, thereby maximizing crop production and reducing the use of unnecessary chemicals.

